include: package:pedantic/analysis_options.1.8.0.yaml
analyzer:
  errors:
    todo: ignore
    unawaited_futures: ignore
linter:
  rules:
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - constant_identifier_names
    - empty_statements
    - prefer_generic_function_type_aliases
    - prefer_typing_uninitialized_variables